In [2]:
import numpy as np 

array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                     [7, 8, 9]])

array2 = np.array([10, 20, 30])

print(array1.shape)
print(array1.ndim)
print(array2.shape)
print(array2.ndim)

result = array1 + array2
print(result)

(3, 3)
2
(3,)
1
[[11 22 33]
 [14 25 36]
 [17 28 39]]
