In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Numpy array:", arr)

print("Array Type:", type(arr))

print( arr * 2)

Numpy array: [1 2 3 4 5]
Array Type: <class 'numpy.ndarray'>
[ 2  4  6  8 10]


In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Numpy array:\n", arr2)

print("array dimension:",arr2.ndim)

print("element at index 0,0:",arr2[0,0])

2D Numpy array:
 [[1 2 3]
 [4 5 6]]
array dimension: 2
element at index 0,0: 1


In [8]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Numpy array:\n", arr3)
print("array dimension:", arr3.ndim)
print("shape of arr3:", arr3.shape)

letter = arr3[1, 0, 1] + arr3[0, 1, 0] + arr2[0 , 2]
print("Accessed element:", letter)

3D Numpy array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
array dimension: 3
shape of arr3: (2, 2, 2)
Accessed element: 12
