In [4]:
import numpy as np

#scalar arithmatic operations

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:")
print(array)

print("\nArray after adding 5:")
print(array + 5)
print("\nArray after subtracting 2:")
print(array - 2)
print("\nArray after multiplying by 3:")
print(array * 3)
print("\nArray after dividing by 2:")
print(array / 2)
print("\nArray after exponentiation by 2:")
print(array ** 2)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Array after subtracting 2:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Array after multiplying by 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

Array after dividing by 2:
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

Array after exponentiation by 2:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [3]:
# Scalar arithmetic operations on a NumPy array

# square root of each element
print(np.sqrt(array))
# natural logarithm of each element
print(np.log(array))
# exponential (e^x) of each element
print(np.exp(array))
# array divided by 3, rounded to nearest integer
print(np.round(array / 3))
# array divided by 3, rounded down (floor)
print(np.floor(array / 3))
# array divided by 3, rounded up (ceiling)
print(np.ceil(array / 3))
# absolute difference from 5 for each element
print(np.abs(array - 5))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0. 1. 1.]
 [1. 2. 2.]
 [2. 3. 3.]]
[[0. 0. 1.]
 [1. 1. 2.]
 [2. 2. 3.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[[4 3 2]
 [1 0 1]
 [2 3 4]]


In [ ]:
#element-wise operations between two arrays 
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("\nSecond Array:")
print(array2)   

print("\nElement-wise addition of two arrays:")
print(array + array2)
print("\nElement-wise subtraction of two arrays:")
print(array - array2)
print("\nElement-wise multiplication of two arrays:")
print(array * array2)
print("\nElement-wise division of two arrays:")
print(array / array2)


Second Array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise addition of two arrays:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise subtraction of two arrays:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise multiplication of two arrays:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise division of two arrays:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [7]:
scores = np.array([85, 90, 78, 92, 88])
max_score = np.max(scores)
min_score = np.min(scores)
average_score = np.mean(scores)

print(f"\nMax Score: {max_score}")
print(f"Min Score: {min_score}")
print(f"Average Score: {average_score}")

print(scores == 90) # Check for scores equal to 90

print(scores > 80)  # Check for scores greater than 80
print(scores < 90)  # Check for scores less than 90

print((scores >= 85) & (scores <= 90))  # Check for scores between 85 and 90 inclusive
print((scores < 80) | (scores > 90))   # Check for scores less than 80 or greater than 90
print(~(scores == 88))  # Check for scores not equal to 88
print(np.isin(scores, [78, 92]))  # Check for scores that are either 78 or 92


Max Score: 92
Min Score: 78
Average Score: 86.6
[False  True False False False]
[ True  True False  True  True]
[ True False  True False  True]
[ True  True False False  True]
[False False  True  True False]
[ True  True  True  True False]
[False False  True  True False]
