In [ ]:
import numpy as np  # import numpy library
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])  # create 4x3 array
# array shape is (4, 3)
# array[start:stop:step]  # slicing notation
print(array[3])  # print 4th row (index 3)
print(array[0:2])  # print rows 0 and 1 (stop is exclusive)
print(array[0:4:3])  # print rows 0 and 3 (step of 3)
print(array[:, -1])  # print last column for all rows
print(array[:,0:2])  # print first two columns for all rows
print(array[1:3, 0:2])  # print subarray: rows 1-2 and columns 0-1
print(array[1:3, 0:2])  # print subarray: rows 1-2 and columns 0-1

[10 11 12]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [10 11 12]]
[ 3  6  9 12]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[4 5]
 [7 8]]
